baseURL = 'https://blog.diver27.com/'
languageCode = 'en-US'
title = 'Ignis Fatuus'
theme = 'typo-custom'
hasCJKLanguage = true

[markup]
	[markup.goldmark]
	renderer.unsafe = true

[params]
description = "The Diver's blog"
homeCollectionTitle = 'Recent'
homeCollection = 'article'
paginationSize = 10
listSummaries = true
homeIntroContent = """愚人火花"""
hideHeader = true
showFooter = true
footerContent = "And the night does not end."
colorPalette = 'gruvebox'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = false
home = "Home"

[[params.menu]]
name = "Archive"
url = "/article"

[[params.menu]]
name = "About"
url = "/about"
