baseURL = 'https://blog.diver27.com/'
languageCode = 'zh-cn'
title = 'Ignis Fatuus'
theme = 'typo'
hasCJKLanguage = true

[params]
homeCollectionTitle = 'Recent'
homeCollection = 'post'
paginationSize = 10
listSummaries = true
breadcrumbs = true
homeIntroContent = """愚人火花"""

[[params.menu]]
name = "Home"
url = "/"

[[params.menu]]
name = "Archive"
url = "/post"

[[params.menu]]
name = "About"
url = "/about"
